// 第一种单例的简单实现
// require('./Singleton1');
// 单例的闭包实现
// require('./Singleton2');
// 透明的单例模式
// require('./Singleton3');
// 用代理实现单例模式
// require('./Singleton4');
// JavaScript中的单例模式
// require('./Singleton5');
// 惰性单例（需要时候才去创建）
// require('./Singleton6');
// 通用的惰性单例
// require('./Singleton7');