// 第一种单例的简单实现
// require('./Singleton1');
// 单例的闭包实现
// require('./Singleton2');
// 透明的单例模式
// require('./Singleton3');
// 用代理实现单例模式
// require('./Singleton4');
// JavaScript中的单例模式
// require('./Singleton5');
// 惰性单例（需要时候才去创建）
// require('./Singleton6');
// 通用的惰性单例
// require('./Singleton7');

// 奖金的最初实现
// require('./Strategy1');
// 组合函数重构代码
// require('./Strategy2');
// 策略模式重构代码
// require('./Strategy3');
// javaScript 中的策略模式
// require('./Strategy4');
// 让小球动起来
// require('./Strategy5');
// 表单校验的第一个版本
// require('./Strategy6');
// 策略模式重构表单校验
// require('./Strategy7');
// 给表单添加多种校验规则
// require('./Strategy8');
// 小明送花
// require('./Proxy1');
// 小明通过B给A送花
// require('./Proxy2');
// 小明通过B给A送花，B监听A的心情，心情好的时候送花
// require('./Proxy3');
// 无虚拟代理图片1
// require('./Proxy4');
// 虚拟代理图片
// require('./Proxy5');
// 不用虚拟代理实现预加载
// require('./Proxy6');
// Check的HTTP请求
// require('./Proxy7');
// 虚拟代理合并HTTP请求
// require('./Proxy8');

// 自定义发布订阅模式
// require('./Observer1');
// 自定义发布订阅模式的改善
// require('./Observer2');
// 发布订阅模式共通化
require('./Observer3');